# Generated by Django 2.0.3 on 2019-03-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EasycomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=255)),
                ('profit_loss_per', models.IntegerField()),
                ('Transferred_amount', models.IntegerField()),
                ('Total_Mc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=255)),
                ('sales_amount', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('Trans_amount', models.IntegerField()),
                ('Commission', models.IntegerField()),
                ('Payment_charge', models.IntegerField()),
                ('pickpack_fee', models.IntegerField()),
            ],
        ),
    ]
